// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropertyManager.Models;

#nullable disable

namespace PropertyManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PropertyManager.Models.Property", b =>
                {
                    b.Property<int>("PropertyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitNum")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PropertyID");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            PropertyID = 1,
                            Address = "123 Eagle Ln",
                            MonthlyRent = 12000.00m,
                            PropertyName = "University Village",
                            UnitNum = "1A"
                        },
                        new
                        {
                            PropertyID = 2,
                            Address = "456 West Side Dr",
                            MonthlyRent = 950.00m,
                            PropertyName = "Suburban Heights",
                            UnitNum = "2B"
                        },
                        new
                        {
                            PropertyID = 3,
                            Address = "910 University Dr",
                            MonthlyRent = 0.00m,
                            PropertyName = "Archies House",
                            UnitNum = "N/A"
                        },
                        new
                        {
                            PropertyID = 4,
                            Address = "915 University Dr",
                            MonthlyRent = 67.00m,
                            PropertyName = "House",
                            UnitNum = "9C"
                        });
                });

            modelBuilder.Entity("PropertyManager.Models.Tenant", b =>
                {
                    b.Property<int>("TenantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenantID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyID")
                        .HasColumnType("int");

                    b.HasKey("TenantID");

                    b.HasIndex("PropertyID");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            TenantID = 1,
                            Email = "archieeagle@usi.edu",
                            FirstName = "Archie",
                            LastName = "BaldEage",
                            PhoneNum = "123-456-7890",
                            PropertyID = 2
                        },
                        new
                        {
                            TenantID = 2,
                            Email = "johndoe@hotmail.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PhoneNum = "098-765-4321",
                            PropertyID = 1
                        },
                        new
                        {
                            TenantID = 3,
                            Email = "janedoe@gmail.com",
                            FirstName = "Jane",
                            LastName = "Doe",
                            PhoneNum = "234-567-1092",
                            PropertyID = 4
                        });
                });

            modelBuilder.Entity("PropertyManager.Models.Tenant", b =>
                {
                    b.HasOne("PropertyManager.Models.Property", "Property")
                        .WithMany("Tenants")
                        .HasForeignKey("PropertyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropertyManager.Models.Property", b =>
                {
                    b.Navigation("Tenants");
                });
#pragma warning restore 612, 618
        }
    }
}
